POST  http://localhost:4000/api/Register
Content-Type: application/json

{
        "username": "Amin",
        "password": "amin",
        "department": "IT"
    }
###

POST http://localhost:4000/api/Login
Content-Type: application/json

{
        "username": "Elham",
        "password": "Hamid"
    }
###
GET http://localhost:4000/api/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJ1c2VybmFtZSI6IkVsaGFtIiwiaWF0IjoxNTkxNTA4MjQ2LCJleHAiOjE1OTE1MDgzNjZ9.Ek9I8PR1pKtm-dj1sPnaVOKxdgl-JTHL4Sp7Mnjxo30
